### ISSUE TITLE
Reverse journal iteration (undo counterpart to redo)

### ISSUE THREAD

**Issue by chrisvest** [sbtourist/Journal.IO#5]
The `redo()` method creates an iterator that traverses the journal in the order the records have been written. It would be nice to be able to traverse the journal in the _reverse_ order, from the most recently written record back to the oldest. This operation could be called `undo()`, though it sounds destructive it matches the `redo()` method.

One way I imagine this could be implemented, is to add a back-pointer to the Location details, that points to the preceding location in the data-file. Perhaps negative values can be used to indicate that the pointer refers to the preceding data-file as well. I have not checked if data-files know the location of their last record.

**Comment by sbtourist** [comment]
An `undo()` method for reverse journal iteration was already on my todo list, so I fully agree with you about that, just adding that we should also provide the latest location to stop undoing (as we provide the first location to start redoing).

Talking about implementation details, `Location`s don't works with pointers, but with absolute identifiers and size of data: in other words forward iteration is implemented by starting at a given `Location` identifier, and moving forward by skipping between `Location`s.
This implementation allows for efficient data compaction, as there are no pointers to be adjusted: hence, I think adding them to implement backward iteration wouldn't be that viable.
So I think there are two alternative options:
1) Providing the last `Location` to undo (starting from the latest one), from there moving forward to collect `Location`s to undo, and then iterating them in reverse order.
2) Adding to the header the size of the previous data segment, so that we can skip backwards.
Former really sounds like a stupid trick, and it also has 2n complexity linear to the number of locations to undo, but the latter would require to adjust size after compaction as backward data could have been changed, so it's practically equal to pointers.
So let's think about it: again, I know the former solution sounds like a trick, but may really be the one providing the best compromise.

Let me know your thoughts.

**Comment by chrisvest** [comment]
I worry that option-1 could potentially incur twice the number of disk seeks than is theoretically necessary, but maybe I shouldn't considering the amount of disk caching in modern OSes and the advent of SSDs with comparatively negligible seek times. It is also appealing that it requires no changes to the storage format, and that it can be easily implemented in terms of the existing redo() APIs. The trade-offs seems to point in its favour.

**Comment by sbtourist** [comment]
It would require x + 1 seeks and y sequential reads, with x and y equal to the number of locations to undo, as it would work the following way:
1) Seek to the last location to undo.
2) Sequentially read/collect locations until latest one.
3) Seek backwards until location read at point #1.
Regarding point #3, seek is avoided in case of not synced reads, as Location objects can cache related data segments.

As you pointed out, this would require no changes in the storage implementation, which is also a big selling point as it preserves compatibility.

In the end, it seems we agree on this implementation: would you like to write it and contribute? Or I could also work on it, probably next week.

Let me know.

**Comment by chrisvest** [comment]
I took a stab at drafting an implementation based on this. You can see it here:
https://github.com/chrisvest/Journal.IO/compare/master...undo

Let me know what you think. I gotta head to my sister birthday now, so I won't have time to work on it more today anyway :)

**Comment by sbtourist** [comment]
I like your implementation, in particular the linked-array implementation :)

Just one minor note: you should move the if-clause at line 746 into the if-clause at line 750: this would reduce if comparisons and hence improve CPU pipelining.

Other than that, just implement the remove method and you're ready to go ;)

Looking forward!

**Comment by chrisvest** [comment]
Thanks. Low memory use and stack were the two things on my mind when I wrote that linked-array code. I doubt moving the if-condition will make a difference (to the hotspot-server JIT) since explicit null-checks are as cheap as the implicit null-checks, like the dereference on line 749.

**Comment by chrisvest** [comment]
Or maybe you're right about the null-check, as the JIT will probably see that `ref` is never null at that location. Second-guessing the JIT is a perilous endeavour :)

**Comment by sbtourist** [comment]
The `ref` is an instance variable which can actually be null when you self-call `next()`, so IMHO the JIT can hardly make any optimization ... but I'm not a JVM expert, so not sure about that.
BTW, better not relying on guessed JIT behaviour :)

**Comment by sbtourist** [comment]
Fixed with issue #6.
